SET SCHEMA DB2CTE;

SELECT * FROM TRAINS;

WITH GET_PATH (PATH, DEPARTURE, ARRIVAL, PRICE)
AS
    (
        SELECT DEPARTURE || '-' || ARRIVAL, DEPARTURE, ARRIVAL, PRICE
        FROM TRAINS
        WHERE DEPARTURE = 'CHICAGO'
        UNION ALL
        SELECT REC.PATH || '-' || T.ARRIVAL, T.DEPARTURE, T.ARRIVAL, REC.PRICE + T.PRICE
        FROM TRAINS T, GET_PATH REC
        WHERE T.DEPARTURE = REC.ARRIVAL
    )
SELECT * FROM GET_PATH;

SELECT * FROM FLIGHTS;
WITH GET_PATH_FLIGHTS (PATH, DEPARTURE, ARRIVAL, PRICE)
AS
    (
        SELECT DEPARTURE || '-' || ARRIVAL, DEPARTURE, ARRIVAL, PRICE
        FROM FLIGHTS
        WHERE DEPARTURE = 'NEW YORK'
        UNION ALL
        SELECT REC.PATH || '-' || F.ARRIVAL, F.DEPARTURE, F.ARRIVAL, REC.PRICE + F.PRICE
        FROM FLIGHTS F, GET_PATH_FLIGHTS REC
        WHERE F.DEPARTURE = REC.ARRIVAL
    )
SELECT DISTINCT PATH, PRICE
FROM GET_PATH_FLIGHTS;

SELECT * FROM TRAINS;
WITH GET_PATH_SOFIA (PATH, DEPARTURE, ARRIVAL, PRICE, NUMBER_TRAINS, NUMBER_FLIGHTS)
    AS
    (
        SELECT DEPARTURE || '-' || ARRIVAL, DEPARTURE, ARRIVAL, PRICE, 0, 1
        FROM FLIGHTS
        WHERE DEPARTURE = 'NEW YORK'
        UNION ALL
        SELECT DEPARTURE || '-' || ARRIVAL, DEPARTURE, ARRIVAL, PRICE, 1, 0
        FROM TRAINS
        WHERE DEPARTURE = 'NEW YORK'
        UNION ALL
        SELECT REC.PATH || '-' || F.ARRIVAL, F.DEPARTURE, F.ARRIVAL, REC.PRICE + F.PRICE, REC.NUMBER_TRAINS, REC.NUMBER_FLIGHTS + 1
        FROM FLIGHTS F, GET_PATH_SOFIA REC
        WHERE F.DEPARTURE = REC.ARRIVAL
        UNION ALL
        SELECT REC.PATH || '-' || F.ARRIVAL, F.DEPARTURE, F.ARRIVAL, REC.PRICE + F.PRICE, REC.NUMBER_TRAINS + 1, REC.NUMBER_FLIGHTS
        FROM TRAINS F, GET_PATH_SOFIA REC
        WHERE F.DEPARTURE = REC.ARRIVAL
    )
SELECT DISTINCT PATH, PRICE, NUMBER_TRAINS, NUMBER_FLIGHTS
FROM GET_PATH_SOFIA
WHERE ARRIVAL = 'SOFIA';

SELECT * FROM EMPLOYEE;
WITH GET_EMPLOYEES (EMP_NAME, EXPERIENCE, LEVEL)
    AS
    (
        SELECT ENAME, YEAR(CURRENT_DATE - EHIREDATE), 1
        FROM EMP
        WHERE MNAME = 'PRES'
        UNION ALL
        SELECT E.ENAME, YEAR(CURRENT_DATE - E.EHIREDATE), REC.LEVEL + 1
        FROM EMP E, GET_EMPLOYEES REC
        WHERE E.MNAME = REC.EMP_NAME
    )
SELECT * FROM GET_EMPLOYEES;