SET SCHEMA FN71852;

-- Скаларна функция за CONTRACTS - връща лихвата на даден клиент по неговото егн
CREATE FUNCTION GET_EGN(CL_SIGN CHAR(5))
RETURNS VARCHAR(10)
RETURN 
	SELECT CLIENT_EGN 
	FROM CONTRACTS
	WHERE CLIENT_SIGNATURE = CL_SIGN;
	
-- Извиквам функцията
VALUES FN71852.GET_EGN('KDD78');

-- Извиквам функцията в заявка
SELECT FN71852.GET_EGN(CLIENT_SIGNATURE) AS CL_EGN
FROM CONTRACTS;

-- Скаларна функция за OFFICES - връща местоположението на офиса по даден негов номер
CREATE FUNCTION GET_LOCATION(OFF_ID CHAR(6))
RETURNS VARCHAR(20)
RETURN
	SELECT LOCATION
	FROM OFFICES 
	WHERE ID = OFF_ID;

-- Извиквам функцията
VALUES FN71852.GET_LOCATION('OFF004');

-- Таблична функция за EMPLOYEES - връща таблица с информация за NAME и OFFICE_ID за служител по неговото егн
CREATE FUNCTION EMPL_DETAILS(E_ID CHAR(6))
RETURNS TABLE(E_NAME VARCHAR(50), OFF_ID CHAR(6))
RETURN
	SELECT NAME, OFFICE_ID 
	FROM EMPLOYEES
	WHERE ID = E_ID;
	
SELECT * FROM TABLE(FN71852.EMPL_DETAILS('EMP220')) E;

-- Таблична функция за APPLICATIONS - връща таблица с информация за NAME, SALARY, COSTS и INCOME за всички клиенти, които имат заплата >= 900
CREATE FUNCTION CLIENT_DETAILS()
RETURNS TABLE(CL_NAME VARCHAR(50), CL_SALARY DOUBLE, CL_COSTS DOUBLE, CL_INCOME DOUBLE)
RETURN
	SELECT CLIENT_NAME, SALARY, COSTS, INCOME
	FROM APPLICATIONS
	WHERE SALARY >= 900;

SELECT * FROM TABLE(FN71852.CLIENT_DETAILS()) C;